// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            BrowserWindow uIBingInternetExplorerWindow = this.UIBingInternetExplorerWindow;
            HtmlEdit uISearchEdit = this.UIBingInternetExplorerWindow.UIGoogleDocument.UISearchEdit;
            #endregion

            // Go to web page 'https://www.google.com/'
            BrowserWindow.Launch(new System.Uri(this.RecordedMethod1Params.UIBingInternetExplorerWindowUrl));

            // Type 'sachin' in 'Search' text box
            uISearchEdit.Text = this.RecordedMethod1Params.UISearchEditText;

            // Type '{Enter}' in 'Search' text box
            Keyboard.SendKeys(uISearchEdit, this.RecordedMethod1Params.UISearchEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinMenuItem uIAddressMenuItem = this.UIBingInternetExplorerWindow.UIAddressComboControlToolBar.UIAddressMenuItem;
            BrowserWindow uIBingInternetExplorerWindow = this.UIBingInternetExplorerWindow;
            HtmlEdit uISearchEdit = this.UIBingInternetExplorerWindow.UIGoogleDocument1.UISearchEdit;
            #endregion

            // Go to web page 'https://www.google.com/'
            BrowserWindow.Launch(new System.Uri(this.RecordedMethod2Params.UIBingInternetExplorerWindowUrl));

            // Type 'kohli' in 'Search' text box
            uISearchEdit.Text = this.RecordedMethod2Params.UISearchEditText;

            // Type '{Enter}' in 'Search' text box
            Keyboard.SendKeys(uISearchEdit, this.RecordedMethod2Params.UISearchEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UIBingInternetExplorerWindow UIBingInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBingInternetExplorerWindow == null))
                {
                    this.mUIBingInternetExplorerWindow = new UIBingInternetExplorerWindow();
                }
                return this.mUIBingInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UIBingInternetExplorerWindow mUIBingInternetExplorerWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://www.google.com/'
        /// </summary>
        public string UIBingInternetExplorerWindowUrl = "https://www.google.com/";
        
        /// <summary>
        /// Type 'sachin' in 'Search' text box
        /// </summary>
        public string UISearchEditText = "sachin";
        
        /// <summary>
        /// Type '{Enter}' in 'Search' text box
        /// </summary>
        public string UISearchEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://www.google.com/'
        /// </summary>
        public string UIBingInternetExplorerWindowUrl = "https://www.google.com/";
        
        /// <summary>
        /// Type 'kohli' in 'Search' text box
        /// </summary>
        public string UISearchEditText = "kohli";
        
        /// <summary>
        /// Type '{Enter}' in 'Search' text box
        /// </summary>
        public string UISearchEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class UIBingInternetExplorerWindow : BrowserWindow
    {
        
        public UIBingInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Bing";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Bing");
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("sachin - Google Search");
            this.WindowTitles.Add("kohli - Google Search");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        
        public UIGoogleDocument1 UIGoogleDocument1
        {
            get
            {
                if ((this.mUIGoogleDocument1 == null))
                {
                    this.mUIGoogleDocument1 = new UIGoogleDocument1(this);
                }
                return this.mUIGoogleDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleDocument mUIGoogleDocument;
        
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        
        private UIGoogleDocument1 mUIGoogleDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.co.in/?gfe_rd=cr&ei=qqrLWPWrC4iBvATXj7jwCw#spf=1";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("sachin - Google Search");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "lst-ib";
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "gsfi lst-d-f";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" title=\"Search\" class=\"gsfi lst-";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUISearchEdit.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISearchEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddressMenuItem
        {
            get
            {
                if ((this.mUIAddressMenuItem == null))
                {
                    this.mUIAddressMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddressMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Address";
                    this.mUIAddressMenuItem.WindowTitles.Add("Bing");
                    #endregion
                }
                return this.mUIAddressMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddressMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.25904.2")]
    public class UIGoogleDocument1 : HtmlDocument
    {
        
        public UIGoogleDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.co.in/?gfe_rd=cr&ei=jK_LWN3cC4e3vATw0oQI#spf=1";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("kohli - Google Search");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "lst-ib";
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "gsfi lst-d-f";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" title=\"Search\" class=\"gsfi lst-";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUISearchEdit.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISearchEdit;
        #endregion
    }
}
